module DomainServices
  module Chat
    class FindMessageService < ApplicationService
      @user: ::User

      @chat: ::Chat

      @content: string

      attr_reader user: ::User

      attr_reader chat: ::Chat

      attr_reader content: string

      def initialize: (::User user, ::Chat chat, string content) -> void

      def call: () -> Array[ChatMessage]

      private

      def global_search?: () -> bool

      def global_search: () -> Array[ChatMessage]

      def chat_search: () -> Array[ChatMessage]
    end
  end
end
