module DomainServices
  module User
    class AuthorizationService < ApplicationService
      @token: string

      attr_reader token: string

      def initialize: (string token) -> void

      def call: () -> ::User?
    end
  end
end
