module DomainServices
  module User
    class BlockUserService < ApplicationService
      @current_user: ::User

      @other_user: ::User

      attr_reader current_user: ::User

      attr_reader other_user: ::User

      def initialize: (::User current_user, ::User other_user) -> void

      def call: () -> BlockedUser
    end
  end
end
