module DomainServices
  module User
    class ChangePasswordService < ApplicationService
      @user: untyped

      @old_password: untyped

      @new_password: untyped

      @new_password_confirmation: untyped

      attr_reader user: untyped

      attr_reader old_password: untyped

      attr_reader new_password: untyped

      attr_reader new_password_confirmation: untyped

      def initialize: (untyped user, untyped old_password, untyped new_password, untyped new_password_confirmation) -> void

      def call: () -> untyped
    end
  end
end
