module DomainServices
  module User
    class ChangePasswordService < ApplicationService
      @user: ::User

      @old_password: string

      @new_password: string

      @new_password_confirmation: string

      attr_reader user: ::User

      attr_reader old_password: string

      attr_reader new_password: string

      attr_reader new_password_confirmation: string

      def initialize: (::User user, string old_password, string new_password, string new_password_confirmation) -> void

      def call: () -> bool
    end
  end
end
